#pragma once
/*
  ^    THIS FILE WAS AUTOGENERATED
 /!\         DO NOT MODIFY
/_'_\ DO NOT COMPLAIN FOR UNREADABLE CODE
*/

#include <Physics/ghostbody.h>
#include <Physics/softscene.h>
#include <Physics/physicalbody.h>
#include <UI/palleteitem.h>
#include <Serialize/serialize_special.h>
