#pragma once

/*
  ^    THIS FILE WAS AUTOGENERATED
 /!\         DO NOT MODIFY
/_'_\ DO NOT COMPLAIN FOR UNREADABLE CODE
*/

#include <Serialize/ser_class_enums.h>
#include "deser_helpers.h"
#include <Serialize/all_serializable.h>

DeserTblEntry physicalbody_deser_tbl[] = {
/*0*/ {},
/*1*/ {.name = "GhostBody", .type = DESER_TBL_SIMPLE, .e_simple = GhostBody::Deserialize},
/*2*/ {.name = "SpringMassBody", .type = DESER_TBL_SIMPLE, .e_simple = SpringMassBody::Deserialize},
};
DeserTblBaseEntry physicalbody_deser_tbl_b[] = {
};

DeserTblEntry obj_deser_tbl[] = {
/*0*/ {},
/*1*/ {.name = "invalid", .type = DESER_TBL_SPECIAL},
/*2*/ {.name = "String", .type = DESER_TBL_SPECIAL},
/*3*/ {.name = "Package", .type = DESER_TBL_SPECIAL},
/*4*/ {.name = "PalleteItem", .type = DESER_TBL_INPLACE, .e_inplace = PalleteItem::Deserialize},
/*5*/ {.name = "SoftScene", .type = DESER_TBL_INPLACE, .e_inplace = SoftScene::Deserialize},
};
DeserTblBaseEntry obj_deser_tbl_b[] = {
/*128*/ {.name = "PhysicalBody", .size = sizeof(physicalbody_deser_tbl)/sizeof(DeserTblEntry), .bsize = sizeof(physicalbody_deser_tbl_b)/sizeof(DeserTblBaseEntry), .e_norm = physicalbody_deser_tbl, .e_base = physicalbody_deser_tbl_b},
};

size_t obj_deser_tbl_size   = sizeof(obj_deser_tbl  ) / sizeof(obj_deser_tbl[0]);
size_t obj_deser_tbl_size_b = sizeof(obj_deser_tbl_b) / sizeof(obj_deser_tbl_b[0]);
