
/*
  ^    THIS FILE WAS AUTOGENERATED
 /!\         DO NOT MODIFY
/_'_\ DO NOT COMPLAIN FOR UNREADABLE CODE
*/

#include <Serialize/ser_class_enums.h>
#include <Serialize/all_serializable.h>

void SpringMassBody::SaveID(DataStorageWriter &data) const {
    PhysicalBody::SaveID(data);
    WRITER_APPEND(data, saved_obj_id_t, SPRMSS_BODY_ID);
}
void TestPolyBody::SaveID(DataStorageWriter &data) const {
    PhysicalBody::SaveID(data);
    WRITER_APPEND(data, saved_obj_id_t, TESTPOLY_BODY_ID);
}
void GhostBody::SaveID(DataStorageWriter &data) const {
    PhysicalBody::SaveID(data);
    WRITER_APPEND(data, saved_obj_id_t, GHOST_BODY_ID);
}
void IGShell::SaveID(DataStorageWriter &data) const {
    PhysicalBody::SaveID(data);
    WRITER_APPEND(data, saved_obj_id_t, IGSHELL_BODY_ID);
}
void EditOnlyBody::SaveID(DataStorageWriter &data) const {
    PhysicalBody::SaveID(data);
    WRITER_APPEND(data, saved_obj_id_t, EDITONLY_BODY_ID);
}
void SoftScene::SaveID(DataStorageWriter &data) const {
    WRITER_APPEND(data, saved_obj_id_t, SAVED_OBJ_SCENE);
}
void PhysicalBody::SaveID(DataStorageWriter &data) const {
    WRITER_APPEND(data, saved_obj_id_t, SAVED_OBJ_PHYSICALBODY);
}
void PalleteItem::SaveID(DataStorageWriter &data) const {
    WRITER_APPEND(data, saved_obj_id_t, SAVED_OBJ_PALLETE_ITEM);
}
