
/*
  ^    THIS FILE WAS AUTOGENERATED
 /!\         DO NOT MODIFY
/_'_\ DO NOT COMPLAIN FOR UNREADABLE CODE
*/

#include <Serialize/ser_class_enums.h>
#include <Serialize/all_serializable.h>

void GhostBody::SaveID(DataStorageWriter &data) const {
    PhysicalBody::SaveID(data);
    PTR_APPEND(data.data, saved_obj_id_t, GHOST_BODY_ID);
}
void PhysicalBody::SaveID(DataStorageWriter &data) const {
    PTR_APPEND(data.data, saved_obj_id_t, PHYSICAL_BODY_ID);
}
void PalleteItem::SaveID(DataStorageWriter &data) const {
    PTR_APPEND(data.data, saved_obj_id_t, PALLETE_ITEM_ID);
}
