
/*
  ^    THIS FILE WAS AUTOGENERATED
 /!\         DO NOT MODIFY
/_'_\ DO NOT COMPLAIN FOR UNREADABLE CODE
*/

#include <Serialize/ser_class_enums.h>
#include <Serialize/all_serializable.h>

void GhostBody::SaveID(DataStorageWriter &data) const {
    PhysicalBody::SaveID(data);
    WRITER_APPEND(data, saved_obj_id_t, GHOST_BODY_ID);
}
void PhysicalBody::SaveID(DataStorageWriter &data) const {
    WRITER_APPEND(data, saved_obj_id_t, SAVED_OBJ_PHYSICALBODY);
}
void PalleteItem::SaveID(DataStorageWriter &data) const {
    WRITER_APPEND(data, saved_obj_id_t, SAVED_OBJ_PALLETE_ITEM);
}
