#pragma once

/*
  ^    THIS FILE WAS AUTOGENERATED
 /!\         DO NOT MODIFY
/_'_\ DO NOT COMPLAIN FOR UNREADABLE CODE
*/

enum SavedPhysicalBodyId { 
    SAVED_PHYSICALBODY_NONE = 0,
    GHOST_BODY_ID = 1,
};
enum SavedObjId { 
    SAVED_OBJ_NONE = 0,
    PHYSICAL_BODY_ID = 128,
    PALLETE_ITEM_ID = 1,
    SAVED_OBJ_STR = 2,
};
